// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using OracleBlazor.Infrastructure.Persistence;

#nullable disable

namespace OracleBlazor.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251026112945_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OracleBlazor.Core.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Category")
                        .HasMaxLength(32)
                        .HasColumnType("NVARCHAR2(32)");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<short>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Location")
                        .HasMaxLength(32)
                        .HasColumnType("NVARCHAR2(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Status")
                        .HasMaxLength(32)
                        .HasColumnType("NVARCHAR2(32)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id")
                        .HasName("PK_ASSETS");

                    b.HasIndex("Tag")
                        .IsUnique()
                        .HasDatabaseName("IX_ASSETS_TAG");

                    b.HasIndex("Category", "Location")
                        .HasDatabaseName("IX_ASSETS_CAT_LOC");

                    b.ToTable("ASSETS", (string)null);
                });

            modelBuilder.Entity("OracleBlazor.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<short>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.HasKey("Id")
                        .HasName("PK_USERS");

                    b.ToTable("USERS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
